site_name: IT杂谈


theme:
    name: readthedocs
#    highlightjs: true


# theme: windmill # 顶层导航
# pip install mkdocs-windmill

#theme: material # 左侧导航 但是又弹效果
# pip install mkdocs-material

# theme: cinder # 顶层导航
# pip install mkdocs-cinder

# theme: rtd-dropdown
# pip install mkdocs-rtd-dropdown

# theme: alabaster
# pip install mkdocs-alabaster

# heme: ivory
# pip install mkdocs-ivory

site_description: 各种互联网软件技术积累总结
site_author: datakv
site_url: https://datakv.github.io

#nav:
#  - Home: index.md

plugins:
    - search
    - awesome-pages
# pip install mkdocs-awesome-pages-plugin
