site_name: 技术杂谈

# theme: windmill
# pip install mkdocs-windmill

#theme: material
# pip install mkdocs-material

theme: cinder
# pip install mkdocs-cinder

site_description: 各种互联网软件技术积累总结
site_author: datakv
site_url: https://datakv.github.io
